<table class="cart" cellspacing="1" width="100%">
	<tbody><tr>
		<th><h3>Product</h3></th>
		<th><h3>Price</h3></th>
		<th width="90"><h3>Quantity</h3></th>
		<th><h3>Sum</h3></th>

		<th width="90"><h3>Shipping Charge</h3></th>
		<th><h3>Total</h3></th>
	</tr>
	
	<tr>
		<td align="center">
			<a href="/store/product/469/product01" title="product01">product01</a><br>
			(
Small, White			)
		</td>

		<td align="center" valign="middle">
			$107.00		</td>
		<td align="center" valign="middle">
			1		</td>
		<td align="center">$107.00</td>
		<td align="center">$0.00</td>
		<td align="center"><strong>$107.00</strong></td>

	</tr>
	<tr>
		<td colspan="6" style="padding: 0pt;" align="center"><div class="hr">&nbsp;</div></td>
	</tr>
	
	<tr>
		<td align="center">
			<a href="/store/product/471/product03" title="product03">product03</a><br>
			(
small			)
		</td>

		<td align="center" valign="middle">
			$200.00		</td>
		<td align="center" valign="middle">
			1		</td>
		<td align="center">$200.00</td>
		<td align="center">$12.00</td>
		<td align="center"><strong>$212.00</strong></td>

	</tr>
	<tr>
		<td colspan="6" style="padding: 0pt;" align="center"><div class="hr">&nbsp;</div></td>
	</tr>
	
	<tr>
		<td colspan="4" style="padding-left: 10px; padding-top: 20px; padding-bottom: 20px;" align="left">
			<input value="" class="edit-list-btn" onclick="document.location.href='/store/view-cart.php';" type="button">
		</td>
	</tr>

</tbody></table>
<h3>Shipping Information</h3>
<form action="checkout.php" method="post" id="checkout-frm" onsubmit="return validateForm(document.getElementById('checkout-frm'));">
<table class="cart" cellspacing="1" width="100%">
	
	
		<tbody><tr>
			<td align="right">
				<label for="shipping-first_name-id">First Name:</label>
			</td>
			<td align="left">
				<input name="shipping_values[first_name]" id="shipping-first_name-id" class="input-shape" value="" style="width: 222px;" required="1" mask="full-name" minlen="2" type="text"><div id="shipping_values[first_name]-msg-box" class="errorMsgBox"></div>

			</td>
		</tr>
		<tr>
			<td align="right">
				<label for="shipping-last_name-id">Last Name:</label>
			</td>
			<td align="left">
				<input name="shipping_values[last_name]" id="shipping-last_name-id" class="input-shape" value="" style="width: 222px;" required="1" mask="full-name" minlen="2" type="text"><div id="shipping_values[last_name]-msg-box" class="errorMsgBox"></div>

			</td>
		</tr>
		<tr>
			<td align="right">
				<label for="shipping-email-id">E-mail:</label>
			</td>
			<td align="left">
				<input name="shipping_values[email]" id="shipping-email-id" class="input-shape" value="" style="width: 222px;" required="1" mask="email" minlen="6" type="text"><div id="shipping_values[email]-msg-box" class="errorMsgBox"></div>

			</td>
		</tr>
		<tr>
			<td align="right">
				<label for="shipping-address_line1-id">Address Line1:</label>
			</td>
			<td align="left">
				<input name="shipping_values[address_line1]" id="shipping-address_line1-id" class="input-shape" value="" style="width: 222px;" required="1" type="text"><div id="shipping_values[address_line1]-msg-box" class="errorMsgBox"></div>

			</td>
		</tr>
		<tr>
			<td align="right">
				<label for="shipping-address_line2-id">Address Line2:</label>
			</td>
			<td align="left">
				<input name="shipping_values[address_line2]" id="shipping-address_line2-id" class="input-shape" value="" style="width: 222px;" type="text">

			</td>
		</tr>
		<tr>
			<td align="right">
				<label for="shipping-city-id">City:</label>
			</td>
			<td align="left">
				<input name="shipping_values[city]" id="shipping-city-id" class="input-shape" value="" style="width: 222px;" required="1" type="text"><div id="shipping_values[city]-msg-box" class="errorMsgBox"></div>

			</td>
		</tr>
		<tr>
			<td align="right">
				<label for="shipping-state-id">State/Province/Region:</label>
			</td>
			<td align="left">
				<!--input name="shipping_values[state]" id="shipping-state-id" class="input-shape" value="" style="width: 222px;" required="1" type="text"-->

				<select name="shipping_values[state]" id="shipping-state-id" style="width: 230px;" required="1">
					<option value=""></option>
				
					<option value="AK">Alaska</option>
					<option value="AL">Alabama</option>
					<option value="AS">American Samoa</option>
					<option value="AZ">Arizona</option>
					<option value="AR">Arkansas</option>

					<option value="CA">California</option>
					<option value="CO">Colorado</option>
					<option value="CT">Connecticut</option>
					<option value="DE">Delaware</option>
					<option value="DC">District of Columbia</option>
					<option value="FM">Federated States of Micronesia</option>

					<option value="FL">Florida</option>
					<option value="GA">Georgia</option>
					<option value="GU">Guam</option>
					<option value="HI">Hawaii</option>
					<option value="ID">Idaho</option>
					<option value="IL">Illinois</option>

					<option value="IN">Indiana</option>
					<option value="IA">Iowa</option>
					<option value="KS">Kansas</option>
					<option value="KY">Kentucky</option>
					<option value="LA">Louisiana</option>
					<option value="ME">Maine</option>

					<option value="MH">Marshall Islands</option>
					<option value="MD">Maryland</option>
					<option value="MA">Massachusetts</option>
					<option value="MI">Michigan</option>
					<option value="MN">Minnesota</option>
					<option value="MS">Mississippi</option>

					<option value="MO">Missouri</option>
					<option value="MT">Montana</option>
					<option value="NE">Nebraska</option>
					<option value="NV">Nevada</option>
					<option value="NH">New Hampshire</option>
					<option value="NJ">New Jersey</option>

					<option value="NM">New Mexico</option>
					<option value="NY">New York</option>
					<option value="NC">North Carolina</option>
					<option value="ND">North Dakota</option>
					<option value="MP">Northern Mariana Islands</option>
					<option value="OH">Ohio</option>

					<option value="OK">Oklahoma</option>
					<option value="OR">Oregon</option>
					<option value="PW">Palau</option>
					<option value="PA">Pennsylvania</option>
					<option value="PR">Puerto Rico</option>
					<option value="RI">Rhode Island</option>

					<option value="SC">South Carolina</option>
					<option value="SD">South Dakota</option>
					<option value="TN">Tennessee</option>
					<option value="TX">Texas</option>
					<option value="UT">Utah</option>
					<option value="VT">Vermont</option>

					<option value="VI">Virgin Islands</option>
					<option value="VA">Virginia</option>
					<option value="WA">Washington</option>
					<option value="WV">West Virginia</option>
					<option value="WI">Wisconsin</option>
					<option value="WY">Wyoming</option>

					<option value="AE">Armed Forces Middle East</option>
					<option value="AA">Armed Forces Americas (except Canada)</option>
					<option value="AP">Armed Forces Pacific</option>
				</select><div id="shipping_values[state]-msg-box" class="errorMsgBox"></div>
			</td>
		</tr>
		<tr>

			<td align="right">
				<label for="shipping-postal-id">Postal Code:</label>
			</td>
			<td align="left">
				<input name="shipping_values[postal]" id="shipping-postal-id" class="input-shape" value="" style="width: 222px;" required="1" minlen="4" maxlen="8" type="text"><div id="shipping_values[postal]-msg-box" class="errorMsgBox"></div>
			</td>
		</tr>
		<tr>

			<td align="right">
				<label for="shipping-fedex-Destination-CountryCode-id">Country:</label>
			</td>
			<td align="left">
				<select name="shipping_values[country]" id="shipping-country-id" style="width: 230px;" required="1" onchange="countryChange(event)" onkeyup="countryChange(event)">
					<option value="US" selected="selected">United States</option>
					<option value="CA">Canada</option>

				</select><div id="shipping_values[country]-msg-box" class="errorMsgBox"></div>
			</td>
		</tr>
		<tr>
			<td align="right">
				<label for="shipping-phone-id">Phone Number:</label>
			</td>
			<td align="left">

				<input name="shipping_values[phone]" id="shipping-phone-id" class="input-shape" value="" style="width: 222px;" required="1" type="text"><div id="shipping_values[phone]-msg-box" class="errorMsgBox"></div>
			</td>
		</tr>
</tbody></table>
<br>
<br>
<h3>Total Charges</h3>
<table class="cart" style="padding: 10px;" cellspacing="1" width="99%">
	<tbody><tr>
		<td align="left">
			PRODUCTS
		</td>

		<td align="right">
			$307.00		</td>
	</tr>
	<tr>
		<td align="left">
			SHIPPING
		</td>
		<td align="right">
			$12.00		</td>

	</tr>
	<tr>
		<td colspan="2" style="padding: 0pt;" align="center"><div class="hr">&nbsp;</div></td>
	</tr>
	<tr>
		<td align="left">
			<strong>TOTAL CHARGES</strong>
		</td>

		<td align="right">
			<strong>$319.00</strong>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="padding-top: 20px; padding-bottom: 20px;" align="center">
			<input value="" class="continue-btn" type="submit">			
		</td>
	</tr>	

</tbody></table>
</form>
 0 