<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<?=$this->headMeta()?>
	<?=$this->headLink()?>
	<?=$this->headTitle()?>
	<?=$this->headStyle()?>
	

	<!--[if IE 6]>
	<link rel="stylesheet" href="/css/ie6.css" type="text/css" />
	<![endif]-->
	<!--[if IE 7]>
	<link rel="stylesheet" href="/css/ie7.css" type="text/css" />
	<![endif]-->
	
	<title></title>
</head>
<body>
<div class="body-wrapper">
	<div class="header-wrapper">
		<div class="header-menu-wrapper">
			<div id="header-menu">
				<?=$this->navigation()->menu();?>
				<a class="fr button-to-store" href="http://<?=$this->fullDomain?>" target="_blank">to store</a>
			</div>
		</div>
		<div class="header-submenu-wrapper">
			<div id="header-submenu">
				<div class="fl"><?=$this->submenu?></div>
				<div class="submenu-right"><div class="fr second-button-link">&nbsp;&nbsp;|&nbsp;&nbsp;<a href="<?=$this->url(array('controller' => 'store','action'=>'logout'))?>">Logout</a></div><button class="button-help fr">help</button></div>
			</div>
		</div>
	</div>
	<?=$this->flashMessages()?>
	<div id="body">
		<?=$this->layout()->content?>
	</div>
</div>
<div class="footer-wrapper">
	<div class="footer">
		<div class="fl">&copy; 2009 SellCast.com.  All Rights Reserved.</div>
		<div class="fr"><a href="<?=$this->url(array('controller' => 'store', 'action' => 'edit-profile'))?>">Account Settings</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#">FAQ</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#">Privacy Policy</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#">Terms of Use</a></div>
	</div>
</div>
<?=$this->headScript()?>
<!--<script type="text/javascript">
		Cufon.replace(['h1','h2','#header-menu ul li a'],{hover: true});
	</script>-->
</body>
</html>