<script type="text/html" id="bigGridHeader">
<% if (header && header.length>0) { %>
	<tr>
		<% for (var i=0;i<header.length;i++) { %>
			<th class="<%=options.classPrefix%><%=header[i].label.toLowerCase()%>">
				<% if (!!header[i].sortField) { %>
					<a href="" rel="<%=header[i].sortField%>" class="sort">
						<span class="sc-grid-header-title"><%=header[i].label%></span>
						<span class="sc-grid-header-sort asc">&nbsp;▲</span>
						<span class="sc-grid-header-sort desc">&nbsp;▼</span>
					</a>
				<% } else {%>
					<%=header[i].label%>
				<%}%>
			</th>
		<%}%>
		<th class="delete-header">&nbsp;</th>
	</tr>
<% } %>
<tr class="hr"><td colspan="<%=(header.length + 1)%>">&nbsp;</td></tr>
</script>
<script type="text/html" id="productsBigGridRows">
	<% for (var i=0;i<rows.length;i++) { %><tr class="extensible" product_id="<%=rows[i].product_id%>" row="<%=i%>">
		<td class="<%=options.classPrefix%>product_name"><button class="button-plus">+</button><%=rows[i].product_name%></td>
		<td class="<%=options.classPrefix%>price">$<%=parseFloat(rows[i].price).toFixed(2)%></td>
		<td class="<%=options.classPrefix%>inventory"><%=rows[i].inventory%></td>
		<td class="<%=options.classPrefix%>status"><%=rows[i].status.capitalize()%></td>
		<td class="delete-order"><button class="button-delete">delete</button></td>
	</tr><% } %>
</script>