<fieldset title="Store elements">
<legend class="grey-h2">Store elements</legend>
<?=$this->element->storeElements?>
</fieldset>
<fieldset title="Structure">
<legend class="grey-h2">Structure</legend>
<?=$this->element->structure?>
</fieldset>
<fieldset title="Embed">
<legend class="grey-h2">Embed</legend>
<?=$this->element->embedForm?>
</fieldset>
<div class="last dl center">
	<div class="center-container save-button-wrapper">
		<?=$this->element->submit?>
		<div class="fl">&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#">Default</a></div>
	</div>
</div>