<?php echo $this->element->referer ?>
<fieldset>
    <div class="clearfix">
        <?=$this->element->domain
            ->setAttrib('class', 'input-xlarge')
            ->setAttrib('placeholder', 'Domain')
            ->setLabel('Domain')?>
    </div>
    <div class="clearfix">
        <?=$this->element->password
            ->setAttrib('class', 'input-xlarge')
            ->setAttrib('placeholder', 'Password')
            ->setLabel('Password')?>
    </div>
    <button class="btn btn-primary pull-right" type="submit">Sign in</button>
</fieldset>