<?php

namespace Proxies\Entities\__CG__\Entities\Order;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Product extends \Entities\Order\Product implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setOrder($order)
    {
        $this->__load();
        return parent::setOrder($order);
    }

    public function getOrder()
    {
        $this->__load();
        return parent::getOrder();
    }

    public function setProductDesc($productDesc)
    {
        $this->__load();
        return parent::setProductDesc($productDesc);
    }

    public function getProductDesc()
    {
        $this->__load();
        return parent::getProductDesc();
    }

    public function setProductId($productId)
    {
        $this->__load();
        return parent::setProductId($productId);
    }

    public function getProductId()
    {
        $this->__load();
        return parent::getProductId();
    }

    public function setProductInfo($productInfo)
    {
        $this->__load();
        return parent::setProductInfo($productInfo);
    }

    public function getProductInfo()
    {
        $this->__load();
        return parent::getProductInfo();
    }

    public function setProductName($productName)
    {
        $this->__load();
        return parent::setProductName($productName);
    }

    public function getProductName()
    {
        $this->__load();
        return parent::getProductName();
    }

    public function setProductPrice($productPrice)
    {
        $this->__load();
        return parent::setProductPrice($productPrice);
    }

    public function getProductPrice()
    {
        $this->__load();
        return parent::getProductPrice();
    }

    public function setQuantity($quantity)
    {
        $this->__load();
        return parent::setQuantity($quantity);
    }

    public function getQuantity()
    {
        $this->__load();
        return parent::getQuantity();
    }

    public function setShippingInfo($shippingInfo)
    {
        $this->__load();
        return parent::setShippingInfo($shippingInfo);
    }

    public function getShippingInfo()
    {
        $this->__load();
        return parent::getShippingInfo();
    }

    public function setShippingPrice($shippingPrice)
    {
        $this->__load();
        return parent::setShippingPrice($shippingPrice);
    }

    public function getShippingPrice()
    {
        $this->__load();
        return parent::getShippingPrice();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'productId', 'productName', 'productDesc', 'productPrice', 'quantity', 'productInfo', 'shippingPrice', 'shippingInfo', 'order');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}