<?php

namespace Proxies\Entities\__CG__\Entities\Store;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Design extends \Entities\Store\Design implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setEmbedHeight($embedHeight)
    {
        $this->__load();
        return parent::setEmbedHeight($embedHeight);
    }

    public function getEmbedHeight()
    {
        $this->__load();
        return parent::getEmbedHeight();
    }

    public function setEmbedWidth($embedWidth)
    {
        $this->__load();
        return parent::setEmbedWidth($embedWidth);
    }

    public function getEmbedWidth()
    {
        $this->__load();
        return parent::getEmbedWidth();
    }

    public function setLayoutType($layoutType)
    {
        $this->__load();
        return parent::setLayoutType($layoutType);
    }

    public function getLayoutType()
    {
        $this->__load();
        return parent::getLayoutType();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setProductsOrder($productsOrder)
    {
        $this->__load();
        return parent::setProductsOrder($productsOrder);
    }

    public function getProductsOrder()
    {
        $this->__load();
        return parent::getProductsOrder();
    }

    public function setProductsPerPage($productsPerPage)
    {
        $this->__load();
        return parent::setProductsPerPage($productsPerPage);
    }

    public function getProductsPerPage()
    {
        $this->__load();
        return parent::getProductsPerPage();
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setUpdateDate()
    {
        $this->__load();
        return parent::setUpdateDate();
    }

    public function getUpdateDate()
    {
        $this->__load();
        return parent::getUpdateDate();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'productsPerPage', 'productsOrder', 'embedWidth', 'embedHeight', 'layoutType', 'updateDate', 'state');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}