<div id="ordersContainer" class="content-narrow">
	<div id="orders"></div>
</div>
<script type="text/html" id="bigGridHeader">
<% if (header && header.length>0) { %>
	<tr>
		<% for (var i=0;i<header.length;i++) { %>
			<th class="<%=header[i]['class']%>">
				<% if (!!header[i].sortField) { %>
					<a href="#" rel="<%=header[i].sortField%>" class="sort">
						<span class="sc-grid-header-title"><%=header[i].label%></span>
						<span class="sc-grid-header-sort asc">▲</span>
						<span class="sc-grid-header-sort desc">▼</span>
					</a>
				<% } else {%>
					<%=header[i].label%>
				<%}%>
			</th>
		<%}%>
		<th class="delete-header">&nbsp;</th>
	</tr>
<% } %>
<tr class="hr"><td colspan="<%=(header.length + 1)%>">&nbsp;</td></tr>
</script>
<script type="text/html" id="ordersBigGridRows">
	<% var __date; for (var i=0;i<rows.length;i++) { %><tr class="extensible" order_id="<%=rows[i].order_id%>" row="<%=i%>">
		<td class="<%=options.classPrefix%>id"><button class="button-plus">+</button>#<%=rows[i].order_id%></td>
		<td class="<%=options.classPrefix%>customer-name"><%=rows[i].who%></td>
		<td class="<%=options.classPrefix%>purchase-date"><% __date = new Date(rows[i].purchase_date * 1000); %><%=__date.toLocaleDateString()%>, <%=__date.toLocaleTimeString()%></td>
		<td class="<%=options.classPrefix%>price">$<%=(rows[i].orderPrice).toFixed(2)%></td>
		<td class="<%=options.classPrefix%>status <%=rows[i].status.toLowerCase()%>"><%=rows[i].status.capitalize()%></td>
		<td class="delete-order"><button class="delete">delete</button></td>
	</tr><% } %>
</script>
<script type="text/html" id="ordersExtended">
	<tr class="extended">
		<td colspan="6">
			<div class="order-info-left fl half">
				<table cellspacing="0" cellpadding="0" border="0">
					<tr>
						<th class="order-product">Product</th>
						<th class="order-quantity">Quantity</th>
						<th class="order-price">Price</th>
					</tr>
					<tr class="hr">
						<td colspan="3">&nbsp;</td>
					</tr>
					<% for (var i=0;i<products.length;i++) {%><tr class="order-product-list">
						<td class="order-product"><%=products[i].product_name%></td>
						<td class="order-quantity"><%=products[i].quantity%></td>
						<td class="order-price">$<%=parseFloat(products[i].price).toFixed(2)%></td>
					</tr><% } %>
					<tr class="order-shipping">
						<td class="order-product">Shipping Total</td>
						<td class="order-quantity">&nbsp;</td>
						<td class="order-price">$<%=parseFloat(shipping_price).toFixed(2)%></td>
					</tr>
					<tr class="order-total">
						<td class="order-product">Order Total</td>
						<td class="order-quantity">&nbsp;</td>
						<td class="order-price">$<%=parseFloat(orderPrice).toFixed(2)%></td>
					</tr>
				</table>
				<div class="order-shipping-control"></div>
			</div>
			<table cellspacing="0" cellpadding="0" border="0" class="half fr">
				<tr>
					<th class="order-shipping-info">Shipping Info</th>
				</tr>
				<tr class="hr">
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td class="order-shipping-info">
						<dl>
							<% if (shipping_price) { %><dt>Total:</dt><dd>$<%=parseFloat(shipping_price).toFixed(2)%></dd><% } %>
							<% if (shippingInfo.first_name) { %><dt>First Name:</dt><dd><%=shippingInfo.first_name%></dd><% } %>
							<% if (shippingInfo.last_name) { %><dt>Last Name:</dt><dd><%=shippingInfo.last_name%></dd><% } %>
							<% if (shippingInfo.email) { %><dt>E-mail:</dt><dd><a href="mailto:<%=shippingInfo.email%>"><%=shippingInfo.email%></a></dd><% } %>
							<% if (shippingInfo.address1 || shippingInfo.address2) { %><dt>Address:</dt><dd><%=(shippingInfo.address1 + '<br />' + shippingInfo.address2)%></dd><% } %>
							<% if (shippingInfo.city) { %><dt>City:</dt><dd><%=shippingInfo.city%></dd><% } %>
							<% if (shippingInfo.state) { %><dt>State/Province/Region:</dt><dd><%=shippingInfo.state%></dd><% } %>
							<% if (shippingInfo.zip) { %><dt>ZIP/Postal Code:</dt><dd><%=shippingInfo.zip%></dd><% } %>
							<% if (shippingInfo.country) { %><dt>Country:</dt><dd><%=shippingInfo.country%></dd><% } %>
							<% if (shippingInfo.phone) { %><dt>Phone Number:</dt><dd><%=shippingInfo.phone%></dd><% } %>
						</dl>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</script>
<script type="text/html" id="orderShippingSummary">
	<h4>Shipment Confirmation Email Sent To Customer</h4>
	<div class="details">
		<p class="status"><%=statusText%></p>
		<% if (shippingInfo.shippingCompany && shippingInfo.shippingCompany != 'none') { %><p class="company">Shipped by &laquo;<%=shippingInfo.shippingCompany%>&raquo;</p><% } %>
		<% if (shippingInfo.trackingNumber) { %><p class="tracking-number">Tracking number: <a target="_blank" href="<%=((shippingInfo.trackingUrl)?shippingInfo.trackingUrl:'#')%>"><%=shippingInfo.trackingNumber%></a></p><% } %>
		<% if (shippingInfo.note && shippingInfo.note != '') { %><i><%=shippingInfo.note%></i><% } %>
	</div>
</script>
<script type="text/html" id="orderShippingEdit">
<?=$this->orderShipping?>
</script>